apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
stringData:
  DB_HOST: "eks-3tier-db.cfsi4888ymu8.ap-south-1.rds.amazonaws.com"
  DB_NAME: "appdb"
  DB_USER: "appadmin"
  DB_PASSWORD: "Weweregoodenough_SK"
  DB_PORT: "5432"
